server:
  port: 9999
spring:
  application:
    name: msconfig
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/Desarrollo/prisma/3dsecure/config
          searchPaths: '{application}'
          username: ${CLOUD_CONFIG_GIT_USER:''}
          password: ${CLOUD_CONFIG_GIT_PASSWORD:''}
          timeout: ${CLOUD_CONFIG_TIMEOUT:4}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
encrypt:
  key: LH5f46UJd|[gKFnf*[in^Zdc4fE@5|

health.config.enabled: false
